const API_BASE_URL = 'https://localhost:7065';

const ENDPOINTS = {
  //PROJECT
  PROJECTS_GET: 'project/getProjects',
  PROJECT_CREATE: 'project/Create',
  PROJECT_DELETE: 'project/Delete',
  //TASK
  TASK_GET: 'task/GetTaskById',
  TASK_REMAIN_TIME: 'task/GetRemainTime',
  TASKS_TOTAL_SPENT_TIME: 'task/GetTotalSpentTimeByProject',
  TASK_CREATE: 'task/Create',
  TASK_EDIT: 'task/Edit',
  TASKS_GET_BY_PROJECT: 'task/GetTasksByProject',
  //TASK COMMENTS
  TASK_COMMENT_EDIT: 'taskcomment/EditComment',
  TASK_COMMENT_CREATE: 'taskcomment/CreateComment',
  TASK_COMMENTS_GET_BY_PROJECT: 'taskcomment/GetCommentByProject',
};

const API_ADDRESSES = {
  //Project
  API_URL_PROJECTS_GET: `${API_BASE_URL}/${ENDPOINTS.PROJECTS_GET}`,
  API_URL_PROJECT_CREATE: `${API_BASE_URL}/${ENDPOINTS.PROJECT_CREATE}`,
  API_URL_PROJECT_DELETE: `${API_BASE_URL}/${ENDPOINTS.PROJECT_DELETE}`,
  //Task
  API_URL_TASK_GET_BY_ID: `${API_BASE_URL}/${ENDPOINTS.TASK_GET}`,
  API_URL_TASKS_TOTAL_SPENT_TIME: `${API_BASE_URL}/${ENDPOINTS.TASKS_TOTAL_SPENT_TIME}`,
  API_URL_TASK_REMAIN_TIME: `${API_BASE_URL}/${ENDPOINTS.TASK_REMAIN_TIME}`,
  API_URL_TASK_CREATE: `${API_BASE_URL}/${ENDPOINTS.TASK_CREATE}`,
  API_URL_TASK_EDIT: `${API_BASE_URL}/${ENDPOINTS.TASK_EDIT}`,
  API_URL_TASKS_GET_BY_PROJECT: `${API_BASE_URL}/${ENDPOINTS.TASKS_GET_BY_PROJECT}`,
  //Task comment
  API_URL_TASK_COMMENT_EDIT: `${API_BASE_URL}/${ENDPOINTS.TASK_COMMENT_EDIT}`,
  API_URL_TASK_COMMENT_CREATE: `${API_BASE_URL}/${ENDPOINTS.TASK_COMMENT_CREATE}`,
  API_URL_TASK_COMMENT_GET_BY_PROJECT_ID: `${API_BASE_URL}/${ENDPOINTS.TASK_COMMENTS_GET_BY_PROJECT}`,
};

export default API_ADDRESSES;